# Site settings
name: Max
title: Max | Full Stack Web Developer
description: A full-stack developer who loves to build things for the web.
url: https://teerpong.me
baseurl: ''
email: teerpong.me@gmail.com
cover: https://teerpong.me/img/og.png
logo: https://teerpong.me/img/emojis/technologist.png
resume: https://teerpong.me/resume.pdf
social:
  - title: twitter
    url: https://twitter.com/bchiang7
    icon: twitter
  - title: facebook
    url: https://instagram.com/bchiang7
    icon: facebook-box
  - title: github
    url: https://github.com/bchiang7
    icon: github
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7
    icon: linkedin-box

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
