# Site settings
name: Max
title: Max | Tech Enthusiast
description: A tech enthusiast who loves to build and engineer scalable and efficient software solutions
url: https://teerpong.netlify.app
baseurl: ''
email: teerpong.me@gmail.com
cover: https://teerpong.netlify.app/img/og.png
logo: https://teerpong.netlify.app/img/emojis/technologist.png
resume: https://teerpong.netlify.app/resume-v6.0.pdf
social:
  - title: twitter
    url: https://twitter.com/sarapmax
    icon: twitter
  - title: facebook
    url: https://facebook.com/sarapmax
    icon: facebook-box
  - title: github
    url: https://github.com/sarapmax
    icon: github
  - title: linkedin
    url: https://www.linkedin.com/in/sarapmax
    icon: linkedin-box

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
